package persistentdata

import (
	"bufio"
	"errors"
	"os"
	"path/filepath"
	"time"

	"github.com/SeaweedbrainCY/jellyfin-newsletter/internal/app"
)

const (
	LastNewsletterFilename = "LAST_NEWSLETTER.txt"
)

func getLastNewsletterFilepath(app *app.ApplicationContext) string {
	baseDirectory, _ := filepath.Split(app.Config.ConfigFilePath)
	return filepath.Join(baseDirectory, LastNewsletterFilename)
}

// GetLastNewsletterDatetime get the time in the LAST_NEWSLETTER.txt file.
// If the file doesn't exist, it returns unix epoch date, without error.
func GetLastNewsletterDatetime(app *app.ApplicationContext) (*time.Time, error) {
	lastNewsletterFilepath := getLastNewsletterFilepath(app)

	file, err := os.Open(lastNewsletterFilepath)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			epoch := time.Date(1970, 1, 1, 0, 0, 0, 0, time.UTC)
			return &epoch, nil
		}
		return nil, err
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	scanner.Scan()
	datetimeStr := scanner.Text()
	datetime, err := time.Parse("2006-01-02T15:04:05.000000", datetimeStr)
	if err != nil {
		return nil, err
	}
	return &datetime, nil
}

func UpdateLastNewsletterDatetime(time time.Time, app *app.ApplicationContext) error {
	lastNewsletterFilepath := getLastNewsletterFilepath(app)
	warningStr := `
	/!\ WARNING /!\

THIS FILE IS AUTOMATICALLY GENERATED BY JELLYFIN NEWSLETTER. MANUALLY EDITING THIS FILE COULD CAUSE BUG OR CRASH.
IF YOU WANT TO RESET THE LAST NEWSLETTER DATE, DELETE THIS FILE AND LET THE PROGRAM CREATE A NEW ONE.`
	filedata := time.Format("2006-01-02T15:04:05.000000") + warningStr
	return os.WriteFile(lastNewsletterFilepath, []byte(filedata), 0600)
}
