package persistentdata

import (
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/SeaweedbrainCY/jellyfin-newsletter/internal/app"
	"github.com/SeaweedbrainCY/jellyfin-newsletter/internal/config"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// newAppWithTempDir builds a minimal ApplicationContext whose ConfigFilePath
// sits inside a temporary directory that is cleaned up after the test.
func newAppWithTempDir(t *testing.T) *app.ApplicationContext {
	t.Helper()
	dir := t.TempDir()
	return &app.ApplicationContext{
		Config: &config.Configuration{
			ConfigFilePath: filepath.Join(dir, "config.yaml"),
		},
	}
}

// writeTestFile creates a file at path with the given content.
func writeTestFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(content), 0600); err != nil {
		t.Fatalf("writeTestFile: %v", err)
	}
}

// Case 1: file does not exist → epoch returned, no error.
func TestGetLastNewsletterDatetime_FileNotExist_ReturnsEpoch(t *testing.T) {
	app := newAppWithTempDir(t)

	got, err := GetLastNewsletterDatetime(app)

	require.NoError(t, err)
	epoch := time.Date(1970, 1, 1, 0, 0, 0, 0, time.UTC)
	assert.Equal(t, epoch.Truncate(time.Second), got.Truncate(time.Second))
}

// Case 2: file exists with a valid datetime → parsed correctly.
func TestGetLastNewsletterDatetime_ValidFile_ReturnsCorrectTime(t *testing.T) {
	app := newAppWithTempDir(t)
	path := getLastNewsletterFilepath(app)

	want := time.Date(2024, 6, 15, 10, 30, 45, 0, time.UTC)
	content := want.Format("2006-01-02T15:04:05.000000") + `

	/!\ WARNING /!\
THIS FILE IS AUTOMATICALLY GENERATED BY JELLYFIN NEWSLETTER.`
	writeTestFile(t, path, content)

	got, err := GetLastNewsletterDatetime(app)

	require.NoError(t, err)
	assert.Equal(t, want.Truncate(time.Second), got.Truncate(time.Second))
}

// Case 3: file exists but contains a malformed datetime → error returned.
func TestGetLastNewsletterDatetime_MalformedDatetime_ReturnsError(t *testing.T) {
	app := newAppWithTempDir(t)
	path := getLastNewsletterFilepath(app)

	writeTestFile(t, path, "not-a-datetime")

	got, err := GetLastNewsletterDatetime(app)

	require.Error(t, err)
	assert.Nil(t, got)
}

// Case 4: file exists but is empty → parse fails, error returned.
func TestGetLastNewsletterDatetime_EmptyFile_ReturnsError(t *testing.T) {
	app := newAppWithTempDir(t)
	path := getLastNewsletterFilepath(app)

	writeTestFile(t, path, "")

	got, err := GetLastNewsletterDatetime(app)

	require.Error(t, err)
	assert.Nil(t, got)
}

// ── UpdateLastNewsletterDatetime ─────────────────────────────────────────────

// Case 5: happy path → file created, first line is correctly formatted, permissions are 0600.
func TestUpdateLastNewsletterDatetime_HappyPath_WritesCorrectContent(t *testing.T) {
	app := newAppWithTempDir(t)
	path := getLastNewsletterFilepath(app)

	want := time.Date(2024, 6, 15, 10, 30, 45, 123456, time.UTC)

	require.NoError(t, UpdateLastNewsletterDatetime(want, app))

	// Verify the file can be round-tripped through the reader.
	got, err := GetLastNewsletterDatetime(app)
	require.NoError(t, err)
	assert.Equal(t, want.Truncate(time.Second), got.Truncate(time.Second))

	// Verify permissions.
	info, err := os.Stat(path)
	require.NoError(t, err)
	assert.Equal(t, os.FileMode(0600), info.Mode().Perm())
}

// Case 6: config points to a non-existent directory → write fails, error returned.
func TestUpdateLastNewsletterDatetime_InvalidDirectory_ReturnsError(t *testing.T) {
	app := &app.ApplicationContext{
		Config: &config.Configuration{
			ConfigFilePath: "/nonexistent/directory/config.yaml",
		},
	}

	err := UpdateLastNewsletterDatetime(time.Now(), app)

	require.Error(t, err)
}
