FROM jellyfin/jellyfin

RUN mkdir /movies
RUN mkdir /tvshows


# Old movie
RUN mkdir "/movies/Star Wars Episode III - Revenge of the Sith (2005)"
RUN touch -d "40 days ago" "/movies/Star Wars Episode III - Revenge of the Sith (2005)/Star Wars Episode III - Revenge of the Sith (2005) Bluray-720p.mp4"

RUN mkdir "/movies/Harry Potter and the Chamber of Secrets (2002)"
RUN touch -d "35 days ago" "/movies/Harry Potter and the Chamber of Secrets (2002)/Harry Potter and the Chamber of Secrets (2002) Bluray-720p Proper.mp4"

# New movies
RUN mkdir "/movies/No Time to Die (2021)"
RUN touch -d "1 days ago" "/movies/No Time to Die (2021)/No Time to Die (2021) Bluray-720p.mp4"

RUN mkdir "/movies/Love Actually (2003)"
RUN touch -d "1 days ago" "/movies/Love Actually (2003)/Love Actually (2003) Bluray-720p.mp4"


# Old series
RUN mkdir -p "/tvshows/House of the Dragon/Season 2/"
RUN touch -d "49 days ago" "/tvshows/House of the Dragon/Season 2/House of the Dragon - S02E01 - A Son for a Son Bluray-720p.mp4"
RUN touch -d "49 days ago" "/tvshows/House of the Dragon/Season 2/House of the Dragon - S02E02 - Rhaenyra the Cruel Bluray-720p.mp4"
RUN touch -d "49 days ago" "/tvshows/House of the Dragon/Season 2/House of the Dragon - S02E03 - The Burning Mill Bluray-720p.mp4"
RUN touch -d "50 days ago" "/tvshows/House of the Dragon/"
RUN touch -d "49 days ago" "/tvshows/House of the Dragon/Season 2/"


# New series - The Last of Us
RUN mkdir -p "/tvshows/The Last of Us/Season 1/"
RUN touch -d "2 days ago" "/tvshows/The Last of Us/Season 1/The Last of Us - S01E01 - When You're Lost in the Darkness Bluray-720p.mp4"
RUN touch -d "2 days ago" "/tvshows/The Last of Us/Season 1/The Last of Us - S01E02 - Infected Bluray-720p.mp4"
RUN touch -d "2 days ago" "/tvshows/The Last of Us/Season 1/The Last of Us - S01E03 - Long Long Time Bluray-720p.mp4"
RUN touch -d "1 days ago" "/tvshows/The Last of Us/Season 1/The Last of Us - S01E04 - Please Hold to My Hand Bluray-720p.mp4"
RUN touch -d "1 days ago" "/tvshows/The Last of Us/Season 1/The Last of Us - S01E05 - Endure and Survive Bluray-720p.mp4"
RUN touch -d "3 days ago" "/tvshows/The Last of Us/"
RUN touch -d "2 days ago" "/tvshows/The Last of Us/Season 1/"


# New series - Severance
RUN mkdir -p "/tvshows/Severance/Season 1/"
RUN touch -d "49 days ago" "/tvshows/Severance/Season 1/Severance - S01E01 - Good News About Hell Bluray-720p.mp4"
RUN touch -d "1 days ago" "/tvshows/Severance/Season 1/Severance - S01E02 - Half Loop Bluray-720p.mp4"
RUN touch -d "1 days ago" "/tvshows/Severance/Season 1/Severance - S01E03 - In Perpetuity Bluray-720p.mp4"
RUN touch -d "50 days ago" "/tvshows/Severance/"
RUN touch -d "49 days ago" "/tvshows/Severance/Season 1/"
