name: "Mediaserver-newsletter docker dev image deployment"

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-dev.[0-9]+'

jobs:
  security_test:
    uses: ./.github/workflows/security_test.yml 
  build_and_publish:
    needs: [security_test]
    name: Build and publish dev image
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: "mediaserver-newsletter"
    steps:
      - uses: actions/checkout@v3
      - name: Build
        working-directory: ./
        run: |
          current_version=${{ github.ref_name }}
          docker build -t $DOCKER_IMAGE_NAME:dev -t $DOCKER_IMAGE_NAME:$current_version .
      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ secrets.USERNAME }} --password-stdin
      - name: Push Docker image to GitHub Container Registry
        run: |
          current_version=${{ github.ref_name }}
          docker tag $DOCKER_IMAGE_NAME:dev ghcr.io/${{ secrets.USERNAME }}/$DOCKER_IMAGE_NAME:dev
          docker tag $DOCKER_IMAGE_NAME:$current_version ghcr.io/${{ secrets.USERNAME }}/$DOCKER_IMAGE_NAME:$current_version
          docker push ghcr.io/${{ secrets.USERNAME }}/$DOCKER_IMAGE_NAME:dev
          docker push ghcr.io/${{ secrets.USERNAME }}/$DOCKER_IMAGE_NAME:$current_version