name: Tag fixed issues on main

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  tag_fixed_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
      pull-requests: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract commit messages
        id: commits
        run: |
          echo "messages<<EOF" >> $GITHUB_OUTPUT
          if [ "${{ github.event_name }}" == "push" ]; then
            git log -1 --pretty=format:"%s%n%b" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "${{ github.event.pull_request.title }}" >> $GITHUB_OUTPUT
            echo "${{ github.event.pull_request.body }}" >> $GITHUB_OUTPUT
          fi
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Find mentioned issues
        id: parse
        run: |
          echo "${{ steps.commits.outputs.messages }}" | grep -Eo '(F|f)ix #([0-9]+)' | sed -E 's/(F|f)ix #//' | sort -u > issue_ids.txt
          echo "issues=$(cat issue_ids.txt | paste -sd ',' -)" >> $GITHUB_OUTPUT

      - name: Add labels to mentioned issues
        if: steps.parse.outputs.issues != ''
        uses: actions/github-script@v7
        with:
          script: |
            const issues = '${{ steps.parse.outputs.issues }}'.split(',');
            for (const issue_number of issues) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: Number(issue_number),
                labels: ["fixed-in-main", "waiting-for-release"]
              });
            }
